# Travis CI
dist: xenial
language: python

python:
  - "3.7"

cache:
  - pip

install:
  - pip install -r scripts/requirements.txt
  - pip install -r scripts/dev_requirements.txt
  - python setup.py develop

script:
  - pytest holidayrules --cov=holidayrules --cov-report term-missing

after_success:
  - coveralls
